### ISSUE TITLE
update Django

### ISSUE THREAD

**Issue by jxstanford** [Solinea/goldstone-server#168]
Currently at 1.6.11, nuf said.

**Comment by jxstanford** [comment]
@stugots this ticket is almost there.  currently there are a handful of tests that fail in the same way.  could you take a look?

To use the branch, you will need to:

```
docker rm $(docker ps -aq)
docker rmi goldstoneserver_gsappdev goldstoneserver_gsdb goldstoneserver_gsdbdvc
bin/start_dev_env.sh
```

The failing tests are all in the tenants module.  Here's the output:

```
======================================================================
FAIL: test_get (goldstone.tenants.tests_user.TenantsIdUsers)
List a tenant's users.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/app/goldstone/tenants/tests_user.py", line 217, in test_get
    self.assertIsInstance(entry["last_login"], basestring)
AssertionError: None is not an instance of <type 'basestring'>

======================================================================
FAIL: test_post (goldstone.tenants.tests_user.TenantsIdUsers)
Create a user in a tenant.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/.tox/py27/local/lib/python2.7/site-packages/mock.py", line 1201, in patched
    return func(*args, **keywargs)
  File "/home/app/goldstone/tenants/tests_user.py", line 294, in test_post
    create(0)
  File "/home/app/goldstone/tenants/tests_user.py", line 252, in create
    "date_joined"])
  File "/home/app/goldstone/test_utils.py", line 188, in check_response_without_uuid
    assert isinstance(response_content[key], basestring)
AssertionError

======================================================================
FAIL: test_get (goldstone.tenants.tests_user.TenantsIdUsersId)
Get a user.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/app/goldstone/tenants/tests_user.py", line 510, in test_get
    extra_keys=["last_login", "date_joined"])
  File "/home/app/goldstone/test_utils.py", line 188, in check_response_without_uuid
    assert isinstance(response_content[key], basestring)
AssertionError

======================================================================
FAIL: test_put (goldstone.tenants.tests_user.TenantsIdUsersId)
Update a user in a tenant.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/app/goldstone/tenants/tests_user.py", line 655, in test_put
    extra_keys=["last_login", "date_joined"])
  File "/home/app/goldstone/test_utils.py", line 188, in check_response_without_uuid
    assert isinstance(response_content[key], basestring)
AssertionError

======================================================================
FAIL: test_put_bad_fields (goldstone.tenants.tests_user.TenantsIdUsersId)
Update a user with missing required fields, or unrecognized
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/app/goldstone/tenants/tests_user.py", line 598, in test_put_bad_fields
    "date_joined"])
  File "/home/app/goldstone/test_utils.py", line 188, in check_response_without_uuid
    assert isinstance(response_content[key], basestring)
AssertionError

----------------------------------------------------------------------
```

**Comment by stugots** [comment]
Test failures fixed.

Why did you stop at Django 1.8.4?

**Comment by jxstanford** [comment]
Mistake.  Appears that latest version is 1.8.7.  Feel free to bump it or I can...

**Comment by stugots** [comment]
There was a Django 1.8.8, but it's not up on Pypi.  Odd.

Django upgraded to 1.8.7.  All unit tests pass.
