### ISSUE TITLE
Update persistent graph fails with exception

### ISSUE THREAD

**Issue by jxstanford** [Solinea/goldstone-server#175]
I've noticed an issue with how OS_AUTH_URL is handled.  I suspect that some modules want a trailing slash while other don't.  In any case, this shows up in prod deployment when there is no trailing slash.  

```Dec 15 21:19:06 gs-ent-1 docker/gsapp[1309]: [2015-12-15 21:19:06,506: ERROR/MainProcess] Task goldstone.core.tasks.update_persistent_graph[2e8534d8-911a-41de-ae29-2f17fc3fe6b8] raised unexpected: Unauthorized()
Dec 15 21:19:06 gs-ent-1 docker/gsapp[1309]: Traceback (most recent call last):
Dec 15 21:19:06 gs-ent-1 docker/gsapp[1309]: File "/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
Dec 15 21:19:06 gs-ent-1 docker/gsapp[1309]: R = retval = fun(*args, **kwargs)
Dec 15 21:19:06 gs-ent-1 docker/gsapp[1309]: File "/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
Dec 15 21:19:06 gs-ent-1 docker/gsapp[1309]: return self.run(*args, **kwargs)
Dec 15 21:19:06 gs-ent-1 docker/gsapp[1309]: File "/home/app/goldstone/core/tasks.py", line 60, in update_persistent_graph
Dec 15 21:19:06 gs-ent-1 docker/gsapp[1309]: update_cinder_nodes()
Dec 15 21:19:06 gs-ent-1 docker/gsapp[1309]: File "/home/app/goldstone/cinder/utils.py", line 34, in update_nodes
Dec 15 21:19:06 gs-ent-1 docker/gsapp[1309]: process_resource_type(nodetype)
Dec 15 21:19:06 gs-ent-1 docker/gsapp[1309]: File "/home/app/goldstone/core/utils.py", line 180, in process_resource_type
Dec 15 21:19:06 gs-ent-1 docker/gsapp[1309]: actual_node_data = nodetype.clouddata()
Dec 15 21:19:06 gs-ent-1 docker/gsapp[1309]: File "/home/app/goldstone/core/models.py", line 1943, in clouddata
Dec 15 21:19:06 gs-ent-1 docker/gsapp[1309]: for entry in get_cinder_client()["client"].qos_specs.list():
Dec 15 21:19:06 gs-ent-1 docker/gsapp[1309]: File "/venv/local/lib/python2.7/site-packages/cinderclient/v2/qos_specs.py", line 51, in list
Dec 15 21:19:06 gs-ent-1 docker/gsapp[1309]: return self._list("/qos-specs", "qos_specs")
Dec 15 21:19:06 gs-ent-1 docker/gsapp[1309]: File "/venv/local/lib/python2.7/site-packages/cinderclient/base.py", line 65, in _list
Dec 15 21:19:06 gs-ent-1 docker/gsapp[1309]: resp, body = self.api.client.get(url)
Dec 15 21:19:06 gs-ent-1 docker/gsapp[1309]: File "/venv/local/lib/python2.7/site-packages/cinderclient/client.py", line 326, in get
Dec 15 21:19:06 gs-ent-1 docker/gsapp[1309]: return self._cs_request(url, 'GET', **kwargs)
Dec 15 21:19:06 gs-ent-1 docker/gsapp[1309]: File "/venv/local/lib/python2.7/site-packages/cinderclient/client.py", line 289, in _cs_request
Dec 15 21:19:06 gs-ent-1 docker/gsapp[1309]: **kwargs)
Dec 15 21:19:06 gs-ent-1 docker/gsapp[1309]: File "/venv/local/lib/python2.7/site-packages/cinderclient/client.py", line 272, in request
Dec 15 21:19:06 gs-ent-1 docker/gsapp[1309]: raise exceptions.from_response(resp, body)
Dec 15 21:19:06 gs-ent-1 docker/gsapp[1309]: Unauthorized```

**Comment by jxstanford** [comment]
This is a good opportunity to bump the openstack client libraries, so I'll do that on a branch now, and see if the problem still exists.  FWIW, I think neutron may also have an issue.

**Comment by jxstanford** [comment]
fixed when openstack clients were updated.
