### ISSUE TITLE
django tests fail in circleci on default settings with 'python manage.py shell'

### ISSUE THREAD

**Issue by heidecke** [Solinea/goldstone-server#189]
Full error follows. Is there a way to make this default work? Would like it to do the initial tests, and then build the containers if successful. Thoughts?

```
cd /home/ubuntu/goldstone-server && { echo 'import json;from django.conf import settings;print('\''OUT: '\'' + settings.TEST_RUNNER)' | python manage.py shell; }
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/virtualenvs/venv-system/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/virtualenvs/venv-system/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/virtualenvs/venv-system/local/lib/python2.7/site-packages/django/core/management/base.py", line 406, in run_from_argv
    connections.close_all()
  File "/home/ubuntu/virtualenvs/venv-system/local/lib/python2.7/site-packages/django/db/utils.py", line 259, in close_all
    for alias in self:
  File "/home/ubuntu/virtualenvs/venv-system/local/lib/python2.7/site-packages/django/db/utils.py", line 253, in __iter__
    return iter(self.databases)
  File "/home/ubuntu/virtualenvs/venv-system/local/lib/python2.7/site-packages/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/virtualenvs/venv-system/local/lib/python2.7/site-packages/django/db/utils.py", line 152, in databases
    self._databases = settings.DATABASES
  File "/home/ubuntu/virtualenvs/venv-system/local/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/home/ubuntu/virtualenvs/venv-system/local/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ubuntu/virtualenvs/venv-system/local/lib/python2.7/site-packages/django/conf/__init__.py", line 113, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")

django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty. ((and (cd "/home/ubuntu/goldstone-server") (group (pipe (echo "'import json;from django.conf import settings;print('\\''OUT: '\\'' + settings.TEST_RUNNER)'") (python manage.py shell))))) returned exit code 1
```

**Comment by jxstanford** [comment]
closed due to timeout

**Comment by maccinza** [comment]
I am facing the exact same issue.
Does anyone have any clues on how to solve it?

p.s.: My settings file contains a SECRET_KEY and it is not empty.

**Comment by heidecke** [comment]
@maccinza It's been a while, IRC we had to pass the full configuration file (in this case goldstone/settings/ci.py) as the minimal.

**Comment by manikumar15** [comment]
raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
