### ISSUE TITLE
six module not found when running 

### ISSUE THREAD

**Issue by heidecke** [Solinea/goldstone-server#205]
Ran `tox -e pylint` within local python virtualenv, python v 2.7.11. Receive error that six module is not found, despite it being installed in site-packages.

```
(goldstone-server)❯ tox -e pylint
pylint installed: alabaster==0.7.7,amqp==1.4.8,anyjson==0.3.3,arrow==0.4.4,astroid==1.4.3,Babel==2.2.0,backports-abc==0.4,backports.ssl-match-hostname==3.5.0.1,beautifulsoup4==4.4.1,billiard==3.3.0.20,celery==3.1.19,certifi==2015.11.20.1,click==6.2,cliff==1.15.0,cmd2==0.6.8,colorama==0.3.3,coverage==3.7.1,debtcollector==1.1.0,decorator==4.0.6,Django==1.8.7,django-admin-bootstrapped==2.5.6,django-extensions==1.5.9,django-filter==0.11.0,django-picklefield==0.3.2,django-polymorphic==0.7.2,django-rest-params==1.0.2,django-rest-swagger==0.3.4,djangorestframework==3.1.0,djoser==0.3.2,docopt==0.6.2,docutils==0.12,drf-extensions==0.2.7,ecdsa==0.13,elasticsearch==1.6.0,elasticsearch-curator==3.1.0,elasticsearch-dsl==0.0.4,Fabric==1.10.2,fake-factory==0.5.3,flower==0.8.2,funcsigs==0.4,functools32==3.2.3.post1,futures==3.0.3,git-up==1.3.0,gitdb==0.6.4,GitPython==1.0.0,iso8601==0.1.11,Jinja2==2.8,jsonpatch==1.12,jsonpointer==1.10,jsonschema==2.5.1,keystoneauth1==2.1.0,kombu==3.0.26,lazy-object-proxy==1.2.1,livereload==2.4.0,lockfile==0.9.1,Markdown==2.6.5,MarkupSafe==0.23,mkdocs==0.14.0,mock==1.0.1,monotonic==0.5,msgpack-python==0.4.6,netaddr==0.7.18,netifaces==0.10.4,networkx==1.9.1,oslo.config==3.2.0,oslo.i18n==3.1.0,oslo.serialization==2.2.0,oslo.utils==3.3.0,paramiko==1.16.0,pbr==1.8.0,pep8==1.5.7,pluggy==0.3.1,prettytable==0.7.2,psycopg2==2.6.1,py==1.4.31,pycadf==2.0.1,pycrypto==2.6.1,pyflakes==0.7.3,Pygments==2.0.2,pylint==1.5.0,pyparsing==2.0.7,python-cinderclient==1.5.0,python-dateutil==2.4.2,python-glanceclient==1.2.0,python-keystoneclient==2.0.0,python-neutronclient==3.1.0,python-novaclient==2.35.0,python-swiftclient==2.7.0,pytz==2015.7,PyYAML==3.11,redis==2.10.5,requests==2.9.1,selenium==2.40.0,simplejson==3.8.1,singledispatch==3.4.0.3,six==1.10.0,smmap==0.9.0,snowballstemmer==1.2.1,Sphinx==1.3.3,sphinx-rtd-theme==0.1.9,stevedore==1.8.0,termcolor==1.1.0,tornado==4.3,tox==2.1.1,unicodecsv==0.14.1,urllib3==1.8,virtualenv==13.1.2,virtualenv-clone==0.2.6,virtualenvwrapper==4.7.1,warlock==1.2.0,wheel==0.26.0,wrapt==1.10.6
pylint runtests: PYTHONHASHSEED='2496743431'
pylint runtests: commands[0] | pylint --rcfile=pylint.cfg goldstone
Traceback (most recent call last):
  File "../../../../../tmp/.tox/pylint/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/private/tmp/.tox/pylint/lib/python2.7/site-packages/pylint/__init__.py", line 22, in run_pylint
    from pylint.lint import Run
  File "/private/tmp/.tox/pylint/lib/python2.7/site-packages/pylint/lint.py", line 42, in <module>
    import six
ImportError: No module named six
ERROR: InvocationError: '/tmp/.tox/pylint/bin/pylint --rcfile=pylint.cfg goldstone'
pylint runtests: commands[1] | pylint --rcfile=pylint.cfg fabfile.py
Traceback (most recent call last):
  File "../../../../../tmp/.tox/pylint/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/private/tmp/.tox/pylint/lib/python2.7/site-packages/pylint/__init__.py", line 22, in run_pylint
    from pylint.lint import Run
  File "/private/tmp/.tox/pylint/lib/python2.7/site-packages/pylint/lint.py", line 42, in <module>
    import six
ImportError: No module named six
ERROR: InvocationError: '/tmp/.tox/pylint/bin/pylint --rcfile=pylint.cfg fabfile.py'
pylint runtests: commands[2] | pylint --rcfile=pylint.cfg post_install.py
Traceback (most recent call last):
  File "../../../../../tmp/.tox/pylint/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/private/tmp/.tox/pylint/lib/python2.7/site-packages/pylint/__init__.py", line 22, in run_pylint
    from pylint.lint import Run
  File "/private/tmp/.tox/pylint/lib/python2.7/site-packages/pylint/lint.py", line 42, in <module>
    import six
ImportError: No module named six
ERROR: InvocationError: '/tmp/.tox/pylint/bin/pylint --rcfile=pylint.cfg post_install.py'
pylint runtests: commands[3] | pylint --rcfile=pylint.cfg configure_stack.py
Traceback (most recent call last):
  File "../../../../../tmp/.tox/pylint/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/private/tmp/.tox/pylint/lib/python2.7/site-packages/pylint/__init__.py", line 22, in run_pylint
    from pylint.lint import Run
  File "/private/tmp/.tox/pylint/lib/python2.7/site-packages/pylint/lint.py", line 42, in <module>
    import six
ImportError: No module named six
ERROR: InvocationError: '/tmp/.tox/pylint/bin/pylint --rcfile=pylint.cfg configure_stack.py'
pylint runtests: commands[4] | pylint --rcfile=pylint.cfg addon_fabfile.py
Traceback (most recent call last):
  File "../../../../../tmp/.tox/pylint/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/private/tmp/.tox/pylint/lib/python2.7/site-packages/pylint/__init__.py", line 22, in run_pylint
    from pylint.lint import Run
  File "/private/tmp/.tox/pylint/lib/python2.7/site-packages/pylint/lint.py", line 42, in <module>
    import six
ImportError: No module named six
ERROR: InvocationError: '/tmp/.tox/pylint/bin/pylint --rcfile=pylint.cfg addon_fabfile.py'
________________________________________________________________________ summary ________________________________________________________________________
ERROR:   pylint: commands failed
```

**Comment by jxstanford** [comment]
no longer an issue.
