### ISSUE TITLE
reconcile_host throws exception during celery task execution

### ISSUE THREAD

**Issue by jxstanford** [Solinea/goldstone-server#22]
Here's the exception details:

```python
[2015-05-15 17:55:03,843: ERROR/MainProcess] Task goldstone.core.tasks.reconcile_hosts[0ece4772-079d-4e8c-8d82-ef99ef983b75] raised unexpected: IntegrityError('null value in column "cloud_id" violates not-null constraint\nDETAIL:  Failing row contains (19, 839e120a-fb2b-11e4-aea5-fa163e5566bb, null, , 2015-05-15 17:55:03.824769+00, 2015-05-15 17:55:03.830016+00).\n',)
Traceback (most recent call last):
  File "/opt/goldstone/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/goldstone/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/goldstone/goldstone/core/tasks.py", line 61, in reconcile_hosts
    services()
  File "/opt/goldstone/goldstone/nova/utils.py", line 183, in reconcile_nova_hosts
    process_resource_type(nodetype)
  File "/opt/goldstone/goldstone/core/utils.py", line 254, in process_resource_type
    name=entry.get("name", ''))
  File "/opt/goldstone/lib/python2.7/site-packages/django/db/models/manager.py", line 157, in create
    return self.get_queryset().create(**kwargs)
  File "/opt/goldstone/lib/python2.7/site-packages/django/db/models/query.py", line 322, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/goldstone/lib/python2.7/site-packages/polymorphic/polymorphic_model.py", line 89, in save
    return super(PolymorphicModel, self).save(*args, **kwargs)
  File "/opt/goldstone/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/goldstone/lib/python2.7/site-packages/django/db/models/base.py", line 572, in save_base
    self._save_parents(cls, using, update_fields)
  File "/opt/goldstone/lib/python2.7/site-packages/django/db/models/base.py", line 597, in _save_parents
    self._save_table(cls=parent, using=using, update_fields=update_fields)
  File "/opt/goldstone/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/opt/goldstone/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/opt/goldstone/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/opt/goldstone/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/goldstone/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
    cursor.execute(sql, params)
  File "/opt/goldstone/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/opt/goldstone/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/goldstone/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
IntegrityError: null value in column "cloud_id" violates not-null constraint
DETAIL:  Failing row contains (19, 839e120a-fb2b-11e4-aea5-fa163e5566bb, null, , 2015-05-15 17:55:03.824769+00, 2015-05-15 17:55:03.830016+00).
```

**Comment by jxstanford** [comment]
For things that don't have an ID, we discussed hashing fields that we can see via the API/CLI.  For example, using the hostname and zone for a Host.  We may want to incorporate region or some other ID (possibly our ID for Cloud) to differentiate between clouds.

Should be safe to use:
* hostname, cloud ID for Host
* availability zone name, and cloud ID for Availability Zone
* flavor name and cloud ID for Flavor

**Comment by stugots** [comment]
I've updated pull request #28. 

Function names fixed.  A couple of additional small bugs fixed.

I altered some of the PolyResource subclasses to generate a unique hash for their "native_id," if their OpenStack attributes didn't contain a unique id.  (E.g., all the types called out in the comments here.) I didn't do this for all the types that need it, because I want to defer some of them (e.g. Keystone's) until we get the client integration going. But I did enough to show that the code to do it will hold together, and appears to be sufficient so far.

I harbor some unease about types such as NovaLimits.  OpenStack appears to treat it as an appendage to another service. NovaLimits' attributes continue only high and low limits, without any pointer to its Nova instance. I.e., "If you're asking for this info, you know where you are in the graph." This isn't how our resource graph code is organized, however. I'll deal with this later.

Please re-review the pull request.

**Comment by jxstanford** [comment]
> I harbor some unease about types such as NovaLimits. OpenStack appears to treat it as an appendage to another service.

I agree with this sentiment.  Limits seem like some attribute of a resource in the graph.  We can continue to review an refine the model.  In the mean time, let's just keep track of them, and dig deep when we have a need.

**Comment by stugots** [comment]
I fixed the identity methods by eliminating the need for them. I've updated the pull request, please review it again.

**Comment by stugots** [comment]
Pull request approved and merged.
