### ISSUE TITLE
exception thrown when trying to run curator via celery task

### ISSUE THREAD

**Issue by jxstanford** [Solinea/goldstone-server#260]
```gsappdev_1 | 2016-01-21 00:06:48,908 INFO      Job starting: delete indices
gsappdev_1 | ERROR: Connection failure.
gsappdev_1 | [2016-01-21 00:06:48,933: ERROR/MainProcess] Task goldstone.core.tasks.prune_es_indices[6c81e4c0-33b6-4183-bc9d-4b7f9a00c97b] raised unexpected: CalledProcessError()
gsappdev_1 | Traceback (most recent call last):
gsappdev_1 |   File "/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
gsappdev_1 |     R = retval = fun(*args, **kwargs)
gsappdev_1 |   File "/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
gsappdev_1 |     return self.run(*args, **kwargs)
gsappdev_1 |   File "/home/app/goldstone/core/tasks.py", line 64, in prune_es_indices
gsappdev_1 |     check_call(curator)
gsappdev_1 |   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
gsappdev_1 |     raise CalledProcessError(retcode, cmd)
gsappdev_1 | CalledProcessError```

Also have an unregistered task that we should remove from the schedule:

```gsappdev_1 | [2016-01-21 00:06:53,208: ERROR/MainProcess] Received unregistered task of type u'goldstone.core.tasks.create_daily_index'.
gsappdev_1 | The message has been ignored and discarded.
gsappdev_1 |
gsappdev_1 | Did you remember to import the module containing this task?
gsappdev_1 | Or maybe you are using relative imports?
gsappdev_1 | Please see http://bit.ly/gLye1c for more information.
gsappdev_1 |
gsappdev_1 | The full contents of the message body was:
gsappdev_1 | {u'utc': True, u'chord': None, u'args': [], u'retries': 0, u'expires': None, u'task': u'goldstone.core.tasks.create_daily_index', u'callbacks': None, u'errbacks': None, u'timelimit': [None, None], u'taskset': None, u'kwargs': {}, u'eta': None, u'id': u'7d761499-5e21-48ea-9076-988cade9a7b2'} (276b)
gsappdev_1 | Traceback (most recent call last):
gsappdev_1 |   File "/venv/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 455, in on_task_received
gsappdev_1 |     strategies[name](message, body,
gsappdev_1 | KeyError: u'goldstone.core.tasks.create_daily_index'```

**Comment by lexjacobs** [comment]
![image](https://cloud.githubusercontent.com/assets/5633015/12599455/e69827d0-c446-11e5-8eae-096fd2fe8889.png)
