### ISSUE TITLE
topology tree doesn't get built if cinder connection raises exception

### ISSUE THREAD

**Issue by jxstanford** [Solinea/goldstone-server#315]
Related question:  why is `update_persistent_graph` using cinderclient at all?  We already have a cinder discovery task that should scrape all the data (or fail to as the case may be).

This may generally apply to failures in other services as well, but our lab system has some issues with cinder that cause an Unauthorized exception from the task:

```Jan 30 18:38:39 goldstone-ent docker/gsapp[774]: [2016-01-30 18:38:39,240: ERROR/MainProcess] Task goldstone.core.tasks.update_persistent_graph[a9b1ee1c-eed2-48d2-a1ed-74da783d4424] raised unexpected: Unauthorized()
Jan 30 18:38:39 goldstone-ent docker/gsapp[774]: Traceback (most recent call last):
Jan 30 18:38:39 goldstone-ent docker/gsapp[774]:  File "/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
Jan 30 18:38:39 goldstone-ent docker/gsapp[774]:    R = retval = fun(*args, **kwargs)
Jan 30 18:38:39 goldstone-ent docker/gsapp[774]:  File "/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
Jan 30 18:38:39 goldstone-ent docker/gsapp[774]:    return self.run(*args, **kwargs)
Jan 30 18:38:39 goldstone-ent docker/gsapp[774]:  File "/home/app/goldstone/core/tasks.py", line 84, in update_persistent_graph
Jan 30 18:38:39 goldstone-ent docker/gsapp[774]:    update_cinder_nodes()
Jan 30 18:38:39 goldstone-ent docker/gsapp[774]:  File "/home/app/goldstone/cinder/utils.py", line 46, in update_nodes
Jan 30 18:38:39 goldstone-ent docker/gsapp[774]:    process_resource_type(nodetype)
Jan 30 18:38:39 goldstone-ent docker/gsapp[774]:  File "/home/app/goldstone/core/utils.py", line 180, in process_resource_type
Jan 30 18:38:39 goldstone-ent docker/gsapp[774]:    actual_node_data = nodetype.clouddata()
Jan 30 18:38:39 goldstone-ent docker/gsapp[774]:  File "/home/app/goldstone/core/models.py", line 1856, in clouddata
Jan 30 18:38:39 goldstone-ent docker/gsapp[774]:    for entry in get_cinder_client().qos_specs.list():
Jan 30 18:38:39 goldstone-ent docker/gsapp[774]:  File "/venv/local/lib/python2.7/site-packages/cinderclient/v1/qos_specs.py", line 51, in list
Jan 30 18:38:39 goldstone-ent docker/gsapp[774]:    return self._list("/qos-specs", "qos_specs")
Jan 30 18:38:39 goldstone-ent docker/gsapp[774]:  File "/venv/local/lib/python2.7/site-packages/cinderclient/base.py", line 73, in _list
Jan 30 18:38:39 goldstone-ent docker/gsapp[774]:    resp, body = self.api.client.get(url)
Jan 30 18:38:39 goldstone-ent docker/gsapp[774]:  File "/venv/local/lib/python2.7/site-packages/cinderclient/client.py", line 103, in get
Jan 30 18:38:39 goldstone-ent docker/gsapp[774]:    return self._cs_request(url, 'GET', **kwargs)
Jan 30 18:38:39 goldstone-ent docker/gsapp[774]:  File "/venv/local/lib/python2.7/site-packages/cinderclient/client.py", line 100, in _cs_request
Jan 30 18:38:39 goldstone-ent docker/gsapp[774]:    return self.request(url, method, **kwargs)
Jan 30 18:38:39 goldstone-ent docker/gsapp[774]:  File "/venv/local/lib/python2.7/site-packages/cinderclient/client.py", line 93, in request
Jan 30 18:38:39 goldstone-ent docker/gsapp[774]:    raise exceptions.from_response(resp, body)
Jan 30 18:38:39 goldstone-ent docker/gsapp[774]: Unauthorized```

**Comment by jxstanford** [comment]
It appears that configure_stack is hosing cinder's api_paste.  Here's the diff.  The IP addresses being put in are from the development environment, so need to be fixed.  Should also look into the differences in keys.

```[root@rdo-kilo-ent cinder(keystone_admin)]# diff api-paste.ini api-paste.ini.1454011477
14,15c14,15
< keystone = request_id faultwrap sizelimit osprofiler authtoken keystonecontext audit apiv1
< keystone_nolimit = request_id faultwrap sizelimit osprofiler authtoken keystonecontext audit apiv1
---
> keystone = request_id faultwrap sizelimit osprofiler authtoken keystonecontext apiv1
> keystone_nolimit = request_id faultwrap sizelimit osprofiler authtoken keystonecontext apiv1
20,21c20,21
< keystone = request_id faultwrap sizelimit osprofiler authtoken keystonecontext audit apiv2
< keystone_nolimit = request_id faultwrap sizelimit osprofiler authtoken keystonecontext audit apiv2
---
> keystone = request_id faultwrap sizelimit osprofiler authtoken keystonecontext apiv2
> keystone_nolimit = request_id faultwrap sizelimit osprofiler authtoken keystonecontext apiv2
62,67c62
< auth_host=172.24.4.100
< service_port=5000
< auth_uri=http://172.24.4.100:5000/
< auth_port=35357
< service_host=172.24.4.100
< service_protocol=http
---
> auth_uri=http://192.168.100.213:5000/v2.0
69,74c64,65
< auth_protocol=http
< admin_password=c915c5d91d614f93
<
< [filter:audit]
< paste.filter_factory = keystonemiddleware.audit:filter_factory
< audit_map_file = /etc/cinder/cinder_api_audit_map.conf
---
> identity_uri=http://192.168.100.213:35357
> admin_password=12f5ae381ddb4c18```

**Comment by jxstanford** [comment]
This api-paste.ini corrects the cinder issues:

```
[filter:authtoken]
paste.filter_factory = keystonemiddleware.auth_token:filter_factory
admin_tenant_name=services
auth_uri=http://192.168.100.213:5000/v2.0
identity_uri=http://192.168.100.213:35357
admin_user=cinder
admin_password=xxxxxxxxxxx```

**Comment by jxstanford** [comment]
configure_stack does not have a context field for this file, and it looks like the template needs to be updated.

**Comment by bhuvan-rk** [comment]
In the celery task update_persistent_graph(), we call update_nodes() for all kinds of resources including Cinder, Keystone, Glance etc. 

But if one of them throws an exception, the others should still be processed and displayed on the topology-tree. 

To catch any exceptions, write a try-catch block around the process_resource_type() function in core/utils.py. 

def process_resource_type(nodetype):
    """Update the persistent Resource graph nodes that are of this type.

try : 
    actual_node_data = nodetype.clouddata()
    persistent_nodes = nodetype.objects.all()
except : 
   # send an empty list out here 

For cinder volumes, this call is going to be in core/models.py : 

class VolumeType(PolyResource):
    """An OpenStack Volume Type."""

    @classmethod
    def clouddata(cls):

To Test : 

Mock the ElasticSearch population & look-up done by cinder client and test that if one of them throws an exception, the others are still going to come through.

**Comment by jxstanford** [comment]
@lexjacobs I've finalized this, and added in some nodes under the Neutron tree in the discovery view.  I've verified that the underlying API calls return data.  Here's the list:
```
bin/gscurl 'http://127.0.0.1:8000/neutron/ports/?region=RegionOne'
bin/gscurl 'http://127.0.0.1:8000/neutron/agents/?region=RegionOne'
bin/gscurl 'http://127.0.0.1:8000/neutron/extensions/?region=RegionOne'
bin/gscurl 'http://127.0.0.1:8000/neutron/routers/?region=RegionOne'
bin/gscurl 'http://127.0.0.1:8000/neutron/networks/?region=RegionOne'
bin/gscurl 'http://127.0.0.1:8000/neutron/quotas/?region=RegionOne'
bin/gscurl 'http://127.0.0.1:8000/neutron/subnets/?region=RegionOne'
bin/gscurl 'http://127.0.0.1:8000/neutron/subnet-pools/?region=RegionOne'
bin/gscurl 'http://127.0.0.1:8000/neutron/floating-ips/?region=RegionOne'
bin/gscurl 'http://127.0.0.1:8000/neutron/security-groups/?region=RegionOne'
bin/gscurl 'http://127.0.0.1:8000/neutron/security-group-rules/?region=RegionOne'
```

You'll need to map those to the appropriate nodes in the tree, and pick an icon.  The icons that we were originally user are a set from opscode chef, but I'm not sure if anything from that set is going to be super descriptive.  I'd say do the best with what we have today, or find some other set that looks reasonable and license friendly.

**Comment by lexjacobs** [comment]
@jxstanford 

```
bin/gscurl -p  'http://127.0.0.1:8000/core/topology/'
```

`resource_list_url` not populated for children of `neutron` .
With current scheme, makes clicking on the icons not produce any data.

**Comment by jxstanford** [comment]
Ok, will look at it tomorrow.

**Comment by lexjacobs** [comment]
@jxstanford 

"security group rules" renders in 'resource info' after you click on the row as a list.
and in the 'resource list', presents as [object Object].

Flatten server-side? Or recommended client adjustment?

![image](https://cloud.githubusercontent.com/assets/5633015/13015775/c271490a-d16f-11e5-966e-140073dfbbd5.png)

![image](https://cloud.githubusercontent.com/assets/5633015/13015795/e461c332-d16f-11e5-97e8-a78d54e81f40.png)

**Comment by jxstanford** [comment]
@lexjacobs let's have the client display only the id and name of each of the rules.  eventually we'll want to find a better way to represent these things, but I don't think it will happen for this release.
