### ISSUE TITLE
compliance opentrail_dump task raises exception

### ISSUE THREAD

**Issue by lexjacobs** [Solinea/goldstone-server#366]
```
gsappdev_1 | [2016-02-16 22:50:06,384: INFO/Worker-2] goldstone.compliance.tasks.opentrail_dump[3fcd0f18-ce98-4142-909b-9c5fed3a90e8]: sample audit entry: {u'_score': 0.0, u'_type': u'identity.authenticate', u'_id': u'a1c73f3b-d4ff-4552-be7c-6a5a763e5213', u'_source': {u'traits': {u'typeURI': u'http://schemas.dmtf.org/cloud/audit/1.0/event', u'eventTime': u'2016-02-16T22:45:03.939281+0000', u'initiator_typeURI': u'service/security/account/user', u'service': u'identity.rdo-kilo', u'eventType': u'activity', u'target_id': u'openstack:bc5025bb-74ee-4417-8b29-99e2e609433c', u'observer_id': u'openstack:eee4890d-20f2-418f-ae91-7a55e6df8ad0', u'initiator_id': u'6248c2002b1a48bdbbb80550cda9ad99', u'target_typeURI': u'service/security/account/user', u'observer_typeURI': u'service/security', u'action': u'authenticate', u'initiator_host_addr': u'172.24.4.100', u'initiator_host_agent': u'python-keystoneclient', u'outcome': u'success', u'id': u'openstack:220375fe-fba3-44f9-b95c-302855c7b793'}, u'raw': {}, u'timestamp': u'2016-02-16T22:45:03.939479'}, u'_index': u'events_2016-02-16'}
gsappdev_1 | [2016-02-16 22:50:06,395: ERROR/MainProcess] Task goldstone.compliance.tasks.opentrail_dump[3fcd0f18-ce98-4142-909b-9c5fed3a90e8] raised unexpected: AttributeError("'module' object has no attribute 'ADMINS'",)
gsappdev_1 | Traceback (most recent call last):
gsappdev_1 |   File "/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
gsappdev_1 |     R = retval = fun(*args, **kwargs)
gsappdev_1 |   File "/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
gsappdev_1 |     return self.run(*args, **kwargs)
gsappdev_1 |   File "/home/app/goldstone/compliance/tasks.py", line 706, in opentrail_dump
gsappdev_1 |     if trail_row.cloud_attributes["owner_email"] and settings.ADMINS:
gsappdev_1 | AttributeError: 'module' object has no attribute 'ADMINS'
gsappdev_1 | [2016-02-16 22:50:06,978: INFO/MainProcess] Task goldstone.glance.tasks.discover_glance_topology[4b81a3b6-13e4-4c91-8035-d8a96ea3dd6b] succeeded in 0.577149312s: None
gsappdev_1 | [2016-02-16 22:50:07,330: INFO/MainProcess] Task goldstone.keystone.tasks.discover_keystone_topology[d71783d8-95ed-4408-8e23-e6c0a3d1e307] succeeded in 0.349278504s: None
gsappdev_1 | [16/Feb/2016 22:50:11] "GET / HTTP/1.1" 200 103173
```

2 trails generated.
Only test_1 seems to be successfully uploading trails to rackspace.

![image](https://cloud.githubusercontent.com/assets/5633015/13094063/557a1f56-d4bd-11e5-8af1-3fd3d8709948.png)

![image](https://cloud.githubusercontent.com/assets/5633015/13094079/74eb1d0e-d4bd-11e5-854f-08a45151c70e.png)

![image](https://cloud.githubusercontent.com/assets/5633015/13094123/af46edf2-d4bd-11e5-938f-353f5b0aadbe.png)

![image](https://cloud.githubusercontent.com/assets/5633015/13094082/7d4ced7e-d4bd-11e5-8516-f1d7760bec66.png)

![image](https://cloud.githubusercontent.com/assets/5633015/13094130/b781c06e-d4bd-11e5-8cdc-9191bbd48035.png)

**Comment by jxstanford** [comment]
this shouldn't generate an exception anymore since the offending code was removed.
