### ISSUE TITLE
api stats query does not seem to honor the index-prefix setting in SavedSearch

### ISSUE THREAD

**Issue by jxstanford** [Solinea/goldstone-server#489]
The saved search that backs the API calls page specifies an index-prefix, but when the query executes, we get a bunch of exceptions from ES that suggest that it's looking at other indices.  To demonstrate, go to the API call viewer page, and watch the output for ES exceptions like:

```gssearch_1 | org.elasticsearch.indices.TypeMissingException: [goldstone_metrics-2016.04.17] type[[api_stats]] missing
gssearch_1 | 	at org.elasticsearch.action.admin.indices.mapping.get.TransportGetFieldMappingsIndexAction.shardOperation(TransportGetFieldMappingsIndexAction.java:112)
gssearch_1 | 	at org.elasticsearch.action.admin.indices.mapping.get.TransportGetFieldMappingsIndexAction.shardOperation(TransportGetFieldMappingsIndexAction.java:60)
gssearch_1 | 	at org.elasticsearch.action.support.single.custom.TransportSingleCustomOperationAction$AsyncSingleAction$3.run(TransportSingleCustomOperationAction.java:248)
gssearch_1 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
gssearch_1 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
gssearch_1 | 	at java.lang.Thread.run(Thread.java:745)
gssearch_1 | [2016-04-17 23:35:11,103][DEBUG][action.admin.indices.mapping.get] [fbaada65879a] failed to execute [org.elasticsearch.action.admin.indices.mapping.get.GetFieldMappingsIndexRequest@55686678]
gssearch_1 | org.elasticsearch.indices.TypeMissingException: [events_2016-04-17] type[[api_stats]] missing
gssearch_1 | 	at org.elasticsearch.action.admin.indices.mapping.get.TransportGetFieldMappingsIndexAction.shardOperation(TransportGetFieldMappingsIndexAction.java:112)
gssearch_1 | 	at org.elasticsearch.action.admin.indices.mapping.get.TransportGetFieldMappingsIndexAction.shardOperation(TransportGetFieldMappingsIndexAction.java:60)
gssearch_1 | 	at org.elasticsearch.action.support.single.custom.TransportSingleCustomOperationAction$AsyncSingleAction$3.run(TransportSingleCustomOperationAction.java:248)
gssearch_1 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
gssearch_1 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
gssearch_1 | 	at java.lang.Thread.run(Thread.java:745)```

The indices mentioned should not be involved in the search.

**Comment by vichargrave** [comment]
This is also happening with logstash index queries but *not* event index queries.  Interestingly the event saved search does not specify a doc_type where the logstash and api_stats saved searches do.

**Comment by jxstanford** [comment]
Interesting observation.  Events come in without modification, and have many different values for type, so I didn’t put a doc_type in the search.  Not sure if/how/why that would be related to the failure to limit the search to the specified index expression though.

**Comment by vichargrave** [comment]
Turns out it had nothing to do with this.  The call to es_indices() in goldstone/models.py was not returning an index so the subsequent call to conn.indices.get_field_mapping() in SavedSearch.field_has_raw() to fail.

**Comment by vichargrave** [comment]
Closed after pull request https://github.com/Solinea/goldstone-server/pull/534 merged.
