### ISSUE TITLE
message improperly assigned to component "events_2016-05

### ISSUE THREAD

**Issue by jxstanford** [Solinea/goldstone-server#536]
```
journal: curl -XPOST 'http://localhost:9200/_bulk?pretty' -d '{"create": {"_type": "audit.http.response", "_id": "557c3282-e8e7-41b9-993a-d14deb3f506f", "_index": "events_2016-05-04"}}#012{"raw": {}, "timestamp": "2016-05-04T17:10:21.510045", "traits": {"typeURI": "http://schemas.dmtf.org/cloud/audit/1.0/event", "eventTime": "2016-05-04T17:10:21.257612+0000", "initiator_host_address": "172.24.4.1", "initiator_typeURI": "service/security/account/user", "service": "nova-api", "target_name": "nova", "eventType": "activity", "reason_code": "200", "target_id": "openstack:4bbd20bbe32b40a8953fc924e43a4d41", "observer_id": "target", "initiator_id": "openstack:51ada37d3ced4320a89c28c63500b31c", "target_typeURI": "service/compute/servers/detail", "initiator_name": "admin", "request_id": "req-1e92609f-0013-4fad-8d47-bba3157de6c7", "action": "read/list", "outcome": "success", "id": "openstack:ff015941-6622-4eb9-a494-9c58f563ba14", "requestPath": "/v2/54bc14b3933e4aec9632d18359c02776/servers/detail?all_tenants=1"}}#012' <155>2016-05-04T17:10:22.369197+00:00 rdo-kilo journal: alarm evaluation cycle failed#0122016-05-04 17:10:22.365 1216 TRACE ceilometer.alarm.service Traceback (most recent call last):#0122016-05-04 17:10:22.365 1216 TRACE ceilometer.alarm.service File "/usr/lib/python2.7/site-packages/ceilometer/alarm/service.py", line 93, in _evaluate_assigned_alarms#0122016-05-04 17:10:22.365 1216 TRACE ceilometer.alarm.service alarms = self._assigned_alarms()#0122016-05-04 17:10:22.365 1216 TRACE ceilometer.alarm.service File "/usr/lib/python2.7/site-packages/ceilometer/alarm/service.py", line 174, in _assigned_alarms#0122016-05-04 17:10:22.365 1216 TRACE ceilometer.alarm.service 'value': True}])#0122016-05-04 17:10:22.365 1216 TRACE ceilometer.alarm.service File "/usr/lib/python2.7/site-packages/ceilometerclient/v2/alarms.py", line 77, in list#0122016-05-04 17:10:22.365 1216 TRACE ceilometer.alarm.service return self._list(options.build_url(self._path(), q))#0122016-05-04 17:10:22.365 1216 TRACE ceilometer.alarm.service File "/usr/lib/python2.7/site-packages/ceilometerclient/common/base.py", line 68, in _list#0122016-05-04 17:10:22.365 1216 TRACE ceilometer.alarm.service resp = self.api.get(url)#0122016-05-04 17:10:22.365 1216 TRACE ceilometer.alarm.service File "/usr/lib/python2.7/site-packages/ceilometerclient/openstack/common/apiclient/client.py", line 355, in get#0122016-05-04 17:10:22.365 1216 TRACE ceilometer.alarm.service return self.client_request("GET", url, **kwargs)#0122016-05-04 17:10:22.365 1216 TRACE ceilometer.alarm.service File "/usr/lib/python2.7/site-packages/ceilometerclient/openstack/common/apiclient/client.py", line 345, in client_request#0122016-05-04 17:10:22.365 1216 TRACE ceilometer.alarm.service self, method, url, **kwargs)#0122016-05-04 17:10:22.365 1216 TRACE ceilometer.alarm.service File "/usr/lib/python2.7/site-packages/ceilometerclient/openstack/common/apiclient/client.py", line 261, in client_request#0122016-05-04 17:10:22.365 1216 TRACE ceilometer.alarm.service method, self.concat_url(endpoint, url), **kwargs)#0122016-05-04 17:10:22.365 1216 TRACE ceilometer.alarm.service File "/usr/lib/python2.7/site-packages/ceilometerclient/openstack/common/apiclient/client.py", line 189, in request#0122016-05-04 17:10:22.365 1216 TRACE ceilometer.alarm.service resp = self.http.request(method, url, **kwargs)#0122016-05-04 17:10:22.365 1216 TRACE ceilometer.alarm.service File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request#0122016-05-04 17:10:22.365 1216 TRACE ceilometer.alarm.service resp = self.send(prep, **send_kwargs)#0122016-05-04 17:10:22.365 1216 TRACE ceilometer.alarm.service File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send#0122016-05-04 17:10:22.365 1216 TRACE ceilometer.alarm.service r = adapter.send(request, **kwargs)#0122016-05-04 17:10:22.365 1216 TRACE ceilometer.alarm.service File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send#0122016-05-04 17:10:22.365 1216 TRACE ceilometer.alarm.service raise ConnectionError(err, request=request)#0122016-05-04 17:10:22.365 1216 TRACE ceilometer.alarm.service ConnectionError: ('Connection aborted.', error(111, 'ECONNREFUSED'))#0122016-05-04 17:10:22.365 1216 TRACE ceilometer.alarm.service
```

**Comment by vichargrave** [comment]
In what index should the messages be stored?

**Comment by jxstanford** [comment]
The messages should still go to the logstash-{date} index as it does today, just need a more accurate pattern for the RFC5424 openstack pattern I believe.  I suspect that this pattern is the place to start looking:

`OPENSTACK_RFC5424_MESSAGE %{OPENSTACK_COMPONENT}: %{OPENSTACK_MESSAGE}|%{OPENSTACK_COMPONENT}: %{GREEDYDATA}`

Let's talk about it on standup today.

**Comment by jxstanford** [comment]
turns out ceilometer is the generator of these messages.  They seem to really have no purpose in syslog.  considering shutting of the redirection of syslog messages from ceilometer since it's not one of the core projects we're interested in monitoring.

it does compel me to continue to refactor the logstash patterns since they are a bit long in the tooth, and we've learned a lot since then (and are pretty close to having a good way to write pattern and filter tests).

**Comment by jxstanford** [comment]
I'm opting for not configuring ceilometer for a few reasons:

1) not a core project for goldstone to observe
2) upcoming goldstone_events would remove other dependencies on ceilometer
3a) future plans to provide our own log shipper will give us more control to do patterning and classification on the sending side, which will simplify receiver side rules.  
3b) This change would be complicated pattern and filter surgery
