### ISSUE TITLE
stack traces being parsed improperly

### ISSUE THREAD

**Issue by jxstanford** [Solinea/goldstone-server#537]
The following trace gets parsed in a way that sets the component to "neutron", but the ERROR message that starts the trace is in the ceilometer logs.  The problem will definitely be in the logstash rules where we try to aggregate the error and trace into a single message with a multiline statement.  

In the case below, you can see the improper behavior by grepping for the actual error message:

```
[root@rdo-kilo log]# cd /var
[root@rdo-kilo log]# grep -rl 'alarm evaluation cycle failed' *
ceilometer/alarm-evaluator.log
messages
```

In this case, and possibly others, it seems that `journal` is catching the TRACE data and logging it to /var/log/messages without the associated ERROR message.  The multiline identifies the TRACE and uses the previous line as the initial line of the message in ES.  

We should build in some better handling to detect that condition, handle it better.  Here's an example of an offending entry in `/var/log/messages`:

```
May  2 07:34:07 rdo-kilo journal: alarm evaluation cycle failed#0122016-05-02 07:34:07.223 1253 TRACE ceilometer.alarm.service Traceback (most recent call last):#0122016-05-02 07:34:07.223 1253 TRACE ceilometer.alarm.service   File "/usr/lib/python2.7/site-packages/ceilometer/alarm/service.py", line 93, in _evaluate_assigned_alarms#0122016-05-02 07:34:07.223 1253 TRACE ceilometer.alarm.service     alarms = self._assigned_alarms()#0122016-05-02 07:34:07.223 1253 TRACE ceilometer.alarm.service   File "/usr/lib/python2.7/site-packages/ceilometer/alarm/service.py", line 174, in _assigned_alarms#0122016-05-02 07:34:07.223 1253 TRACE ceilometer.alarm.service     'value': True}])#0122016-05-02 07:34:07.223 1253 TRACE ceilometer.alarm.service   File "/usr/lib/python2.7/site-packages/ceilometerclient/v2/alarms.py", line 77, in list#0122016-05-02 07:34:07.223 1253 TRACE ceilometer.alarm.service     return self._list(options.build_url(self._path(), q))#0122016-05-02 07:34:07.223 1253 TRACE ceilometer.alarm.service   File "/usr/lib/python2.7/site-packages/ceilometerclient/common/base.py", line 68, in _list#0122016-05-02 07:34:07.223 1253 TRACE ceilometer.alarm.service     resp = self.api.get(url)#0122016-05-02 07:34:07.223 1253 TRACE ceilometer.alarm.service   File "/usr/lib/python2.7/site-packages/ceilometerclient/openstack/common/apiclient/client.py", line 355, in get#0122016-05-02 07:34:07.223 1253 TRACE ceilometer.alarm.service     return self.client_request("GET", url, **kwargs)#0122016-05-02 07:34:07.223 1253 TRACE ceilometer.alarm.service   File "/usr/lib/python2.7/site-packages/ceilometerclient/openstack/common/apiclient/client.py", line 345, in client_request#0122016-05-02 07:34:07.223 1253 TRACE ceilometer.alarm.service     self, method, url, **kwargs)#0122016-05-02 07:34:07.223 1253 TRACE ceilometer.alarm.service   File "/usr/lib/python2.7/site-packages/ceilometerclient/openstack/common/apiclient/client.py", line 261, in client_request#0122016-05-02 07:34:07.223 1253 TRACE ceilometer.alarm.service     method, self.concat_url(endpoint, url), **kwargs)#0122016-05-02 07:34:07.223 1253 TRACE ceilometer.alarm.service   File "/usr/lib/python2.7/site-packages/ceilometerclient/openstack/common/apiclient/client.py", line 189, in request#0122016-05-02 07:34:07.223 1253 TRACE ceilometer.alarm.service     resp = self.http.request(method, url, **kwargs)#0122016-05-02 07:34:07.223 1253 TRACE ceilometer.alarm.service   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request#0122016-05-02 07:34:07.223 1253 TRACE ceilometer.alarm.service     resp = self.send(prep, **send_kwargs)#0122016-05-02 07:34:07.223 1253 TRACE ceilometer.alarm.service   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send#0122016-05-02 07:34:07.223 1253 TRACE ceilometer.alarm.service     r = adapter.send(request, **kwargs)#0122016-05-02 07:34:07.223 1253 TRACE ceilometer.alarm.service   File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send#0122016-05-02 07:34:07.223 1253 TRACE ceilometer.alarm.service     raise ConnectionError(err, request=request)#0122016-05-02 07:34:07.223 1253 TRACE ceilometer.alarm.service ConnectionError: ('Connection aborted.', error(111, 'ECONNREFUSED'))#0122016-05-02 07:34:07.223 1253 TRACE ceilometer.alarm.service
```

and what happens to it when it gets to ElasticSearch:

```
2016-05-04T14:17:22-07:00	INFO	neutron	rdo-kilo	journal: 2016-05-04 21:17:22.609 2978 INFO neutron.wsgi [req-d7207559-143f-48a0-8517-e42de6958f80 ] 172.24.4.100 - - [04/May/2016 21:17:22] "GET /v2.0/ports.json?network_id=f1b56c48-887c-47c3-a811-912b8f42ab9d&device_owner=network%3Adhcp HTTP/1.1" 200 948 0.019352 <155>2016-05-04T21:17:23.914391+00:00 rdo-kilo journal: alarm evaluation cycle failed#0122016-05-04 21:17:23.910 1216 TRACE ceilometer.alarm.service Traceback (most recent call last):#0122016-05-04 21:17:23.910 1216 TRACE ceilometer.alarm.service File "/usr/lib/python2.7/site-packages/ceilometer/alarm/service.py", line 93, in _evaluate_assigned_alarms#0122016-05-04 21:17:23.910 1216 TRACE ceilometer.alarm.service alarms = self._assigned_alarms()#0122016-05-04 21:17:23.910 1216 TRACE ceilometer.alarm.service File "/usr/lib/python2.7/site-packages/ceilometer/alarm/service.py", line 174, in _assigned_alarms#0122016-05-04 21:17:23.910 1216 TRACE ceilometer.alarm.service 'value': True}])#0122016-05-04 21:17:23.910 1216 TRACE ceilometer.alarm.service File "/usr/lib/python2.7/site-packages/ceilometerclient/v2/alarms.py", line 77, in list#0122016-05-04 21:17:23.910 1216 TRACE ceilometer.alarm.service return self._list(options.build_url(self._path(), q))#0122016-05-04 21:17:23.910 1216 TRACE ceilometer.alarm.service File "/usr/lib/python2.7/site-packages/ceilometerclient/common/base.py", line 68, in _list#0122016-05-04 21:17:23.910 1216 TRACE ceilometer.alarm.service resp = self.api.get(url)#0122016-05-04 21:17:23.910 1216 TRACE ceilometer.alarm.service File "/usr/lib/python2.7/site-packages/ceilometerclient/openstack/common/apiclient/client.py", line 355, in get#0122016-05-04 21:17:23.910 1216 TRACE ceilometer.alarm.service return self.client_request("GET", url, **kwargs)#0122016-05-04 21:17:23.910 1216 TRACE ceilometer.alarm.service File "/usr/lib/python2.7/site-packages/ceilometerclient/openstack/common/apiclient/client.py", line 345, in client_request#0122016-05-04 21:17:23.910 1216 TRACE ceilometer.alarm.service self, method, url, **kwargs)#0122016-05-04 21:17:23.910 1216 TRACE ceilometer.alarm.service File "/usr/lib/python2.7/site-packages/ceilometerclient/openstack/common/apiclient/client.py", line 261, in client_request#0122016-05-04 21:17:23.910 1216 TRACE ceilometer.alarm.service method, self.concat_url(endpoint, url), **kwargs)#0122016-05-04 21:17:23.910 1216 TRACE ceilometer.alarm.service File "/usr/lib/python2.7/site-packages/ceilometerclient/openstack/common/apiclient/client.py", line 189, in request#0122016-05-04 21:17:23.910 1216 TRACE ceilometer.alarm.service resp = self.http.request(method, url, **kwargs)#0122016-05-04 21:17:23.910 1216 TRACE ceilometer.alarm.service File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 465, in request#0122016-05-04 21:17:23.910 1216 TRACE ceilometer.alarm.service resp = self.send(prep, **send_kwargs)#0122016-05-04 21:17:23.910 1216 TRACE ceilometer.alarm.service File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 573, in send#0122016-05-04 21:17:23.910 1216 TRACE ceilometer.alarm.service r = adapter.send(request, **kwargs)#0122016-05-04 21:17:23.910 1216 TRACE ceilometer.alarm.service File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send#0122016-05-04 21:17:23.910 1216 TRACE ceilometer.alarm.service raise ConnectionError(err, request=request)#0122016-05-04 21:17:23.910 1216 TRACE ceilometer.alarm.service ConnectionError: ('Connection aborted.', error(111, 'ECONNREFUSED'))#0122016-05-04 21:17:23.910 1216 TRACE ceilometer.alarm.service
```

**Comment by jxstanford** [comment]
This looks like a good approach:  https://sematext.com/blog/2015/05/26/handling-stack-traces-with-logstash/

**Comment by jxstanford** [comment]
This seems to be related to rsyslog connecting to journal.  We can probably tighten up the pattern for a TRACE line to resolve this, but I think this might be a change to default rsyslog behavior in CentOS 7.1.  Testing that theory now.

**Comment by jxstanford** [comment]
Well, I didn't confirm that it's new behavior, but I think I fixed it.  The multiline coded uses a pattern to determine if the line under inspection is part of a multiline message.  The pattern can be found anywhere in the line, so I added a ^ to it to ensure that we're not picking up TRACE messages that have already been aggregated into an error.
