### ISSUE TITLE
error when starting goldstone, even after deleting and reimporting docker images.

### ISSUE THREAD

**Issue by lexjacobs** [Solinea/goldstone-server#573]
## Current Behavior

```
jaldaz [11:49 AM] 
after build finish I get these errors

gstask_1   | [2016-05-19 19:48:00,162: ERROR/MainProcess] Task
goldstone.core.tasks.service_status_check[626ba0dc-322f-4768-aa37-fcef5e3b5264] raised
unexpected: KeyError('aggregations',)
gstask_1   | Traceback (most recent call last):
gstask_1   |   File "/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
gstask_1   |     R = retval = fun(*args, **kwargs)
gstask_1   |   File "/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
gstask_1   |     return self.run(*args, **kwargs)
gstask_1   |   File "/home/app/goldstone/core/tasks.py", line 190, in service_status_check
gstask_1   |     found_services_by_host = result['aggregations']['per_host']['buckets']
gstask_1   | KeyError: 'aggregations'

alex.jacobs [11:49 AM] 
if you let it continue to run does it eventually clear up?

[11:49] 
or does the server stop?

jaldaz [11:49 AM] 
nope, over and over again the same issues

jaldaz [11:50 AM] 
and dashboard doesnt work at all
```

@vichargrave wondering if you have any insight into the error above?

```

jxstanford [4:52 PM] 
That message indicates that the query that is looking for services in API calls is not finding any, so
either the query is broken or logs aren't flowing.  Get Vic involved to debug that if necessary.
```

**Comment by joraldaz** [comment]
If it helps, I wouldnt have any issue in give you ssh access by a public ip and debug it on my enviroment.

**Comment by joraldaz** [comment]
`jor@jor-laptop ~/devel/goldstone-server $ docker images -a
REPOSITORY                 TAG                                   IMAGE ID            CREATED             SIZE
<none>                     <none>                                8218f5818838        3 days ago          687.6 MB
<none>                     <none>                                9aabce5bb7be        3 days ago          687.6 MB
goldstoneserver_gstask     latest                                ae9039f9066a        3 days ago          687.6 MB
<none>                     <none>                                56551e28f246        3 days ago          687.6 MB
<none>                     <none>                                8279461320a5        3 days ago          687.6 MB
<none>                     <none>                                5e9024adf429        3 days ago          457.8 MB
<none>                     <none>                                686a56843bfe        3 days ago          457.8 MB
goldstoneserver_gslog      latest                                4dd9971509d4        3 days ago          457.8 MB
<none>                     <none>                                300887b68ee3        3 days ago          454.5 MB
<none>                     <none>                                5769a3ce5213        3 days ago          451.2 MB
<none>                     <none>                                e7da966b70c1        3 days ago          451.3 MB
goldstoneserver_gstaskq    latest                                bb844ee589d7        3 days ago          148.6 MB
goldstoneserver_gssearch   latest                                ed8ad6d8ad38        3 days ago          318.9 MB
<none>                     <none>                                32a9ed7c5867        3 days ago          318.9 MB
<none>                     <none>                                17f27018a57f        3 days ago          318.8 MB
<none>                     <none>                                29843899856f        3 days ago          318.8 MB
<none>                     <none>                                0b5474f15cdb        3 days ago          318.8 MB
<none>                     <none>                                922b92b14095        3 days ago          282.1 MB
<none>                     <none>                                aee410dbeccc        3 days ago          274.6 MB
goldstoneserver_gsdb       latest                                4c379cdfa87a        3 days ago          274.6 MB
<none>                     <none>                                100493ae4c48        3 days ago          274.6 MB
<none>                     <none>                                c1811aac301b        3 days ago          274.6 MB
<none>                     <none>                                6e2e4b945599        3 days ago          274.6 MB
kibana                     4.1                                   a08f390218fe        4 days ago          234.8 MB
solinea/goldstone-base     1.1.1-SNAPSHOT.256.g792adab.develop   15403f6e137c        11 days ago         687.6 MB
logstash                   2.1                                   51a7a86bcc90        2 weeks ago         451.2 MB
solinea/postgres           9.4                                   52fa257a912f        4 weeks ago         274.6 MB
solinea/elasticsearch      1.7.1                                 821f45c9a0be        9 weeks ago         282.1 MB
solinea/redis              3.0.4                                 20fbe8b51989        7 months ago        148.6 MB
`

**Comment by lexjacobs** [comment]
per @joraldaz 
bin/configure_vbox.sh didnt work
```
jor@jor-laptop ~/devel/goldstone-server $ bin/configure_vbox.sh

***********************************************************************
    A host network with address 172.24.4.1 already exists.
    You can find it using 'VBoxManage list --long hostonlyifs'.
    After you find the name, adjust your development OpenStack instance
    network settings for interface 2 accordingly.
***********************************************************************


***********************************************************************
    A NAT network with name GoldstoneDevNAT already exists.
    You can inspect it using 'VBoxManage list --long natnetworks'.
    Adjust your development OpenStack instance network settings
    for interface 1 accordingly.
***********************************************************************
Finished configuring VM network interfaces
Host does not exist: "default"
processing rule: es_9200_local,tcp,,9200,,9200
VBoxManage: error: Could not find a registered machine named 'default'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 486 of file VBoxManageModifyVM.cpp
processing rule: es_9300_local,tcp,,9300,,9300
VBoxManage: error: Could not find a registered machine named 'default'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 486 of file VBoxManageModifyVM.cpp
processing rule: logstash_syslog_local,tcp,,5514,,5514
VBoxManage: error: Could not find a registered machine named 'default'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 486 of file VBoxManageModifyVM.cpp
processing rule: logstash_metrics_local,udp,,5516,,5516
VBoxManage: error: Could not find a registered machine named 'default'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 486 of file VBoxManageModifyVM.cpp
processing rule: logstash_agent_local,tcp,,5516,,5516
VBoxManage: error: Could not find a registered machine named 'default'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 486 of file VBoxManageModifyVM.cpp
processing rule: logstash_internal_local,tcp,,5517,,5517
VBoxManage: error: Could not find a registered machine named 'default'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 486 of file VBoxManageModifyVM.cpp
processing rule: postgres_local,tcp,,5432,,5432
VBoxManage: error: Could not find a registered machine named 'default'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 486 of file VBoxManageModifyVM.cpp
processing rule: redis_local,tcp,,6379,,6379
VBoxManage: error: Could not find a registered machine named 'default'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 486 of file VBoxManageModifyVM.cpp
processing rule: kibana_local,tcp,,5601,,5601
VBoxManage: error: Could not find a registered machine named 'default'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 486 of file VBoxManageModifyVM.cpp
processing rule: gs_8000_local,tcp,,8000,,8000
VBoxManage: error: Could not find a registered machine named 'default'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 486 of file VBoxManageModifyVM.cpp
processing rule: gs_8443_local,tcp,,8443,,8443
VBoxManage: error: Could not find a registered machine named 'default'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 486 of file VBoxManageModifyVM.cpp
processing rule: flower_local,tcp,,5555,,5555
VBoxManage: error: Could not find a registered machine named 'default'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 486 of file VBoxManageModifyVM.cpp
Encountered errors setting up NAT rules for default
```

**Comment by joraldaz** [comment]
This is what after many tries, worked for me.
```

Clean Enviroment if neeed and leave it ready

$ docker rm -f $(docker ps -qa)
$ docker rmi -f $(docker images  | grep a | awk '{print $3}')
Delete RDO from virtual boc
$ pkill -f VirtualBox
import RDO on VirtualBox
Start RDO, I needed to allow promiscuous mode for RDO networks otherwise it wont start
$ workon goldstone-server
$ pip install -r docker/goldstone-base/config/requirements.txt
$ pip install -r docker/goldstone-base/config/test-requirements.txt

$ bin/start_dev_env.sh --app-edition=oss --docker-vm=none
(wait for build arround 5 minutes)

$ docker exec -it goldstoneserver_gsapp_1 bash
(venv) $ fab -f post_install.py -H 172.24.4.100 configure_stack:172.24.4.1,True,True
(venv) $ exit

Stop build process, Ctrl+C

docker rm -f $(docker ps -qa)
pkill -f VirtualBox

bin/start_dev_env.sh --app-edition=oss --docker-vm=none --app-location=local
```

**Comment by jxstanford** [comment]
closing.  I think this was a combo of issues including replacing RDO image, but not running configure_stack.
